---
# Source: hello/templates/deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: hello
    ms: hello
    version: v1
---
# Source: hello/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  selector:
    matchLabels:
      app: hello
      ms: hello
      version: v1
  replicas: 2 
  template:
    metadata:
      labels:
        app: hello 
        ms: hello
        version: v1
    spec:
      containers:
      - name: hello
        image: sndemo/hello:v1 
        imagePullPolicy: IfNotPresent
        env:
          - name: HOST 
            value: 0.0.0.0
          - name: PORT 
            value: "80"
          - name: SERVICE_NAME
            value: hello
          - name: VERSION
            value: v1
          - name: NAME_URL
            value: http://name/name 
          - name: PHONE_URL
            value: http://phone/phone 
        ports:
        - containerPort: 80
